import {space_grotesk } from './utils/fonts'
import "./globals.css";
import SmoothScrolling from "@/components/SmoothScrolling";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${space_grotesk} antialiased`}
      >
        <SmoothScrolling><main className="space_grotesk">{children}</main></SmoothScrolling>
        
      </body>
    </html>
  );
}
